### ISSUE TITLE
Scripts don't work

### ISSUE THREAD

**Issue by Bill-Armstrong** [Bang3DEngine/Bang#94]
Does one have to install qt4?  I have Kubuntu 16.10 and Qt5.7.1 and I get the following:
arms@Gallus:~/GitHub/Bang project/Bang$ ./scripts/fullCompile.sh EDITOR RELEASE_MODE
Full compiling will take a little longer...
You have 5 seconds to stop it.
5...4...3...2...1...Go!
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory
make: *** No rule to make target 'clean'.  Stop.
rm: cannot remove 'Qt_MOCs/*': No such file or directory
rm: cannot remove 'bin/objEditor/*': No such file or directory
rm: cannot remove 'bin/objGame/*': No such file or directory
BUILD_MODE on compile.sh:       'EDITOR'
RELEASE_OR_DEBUG on compile.sh: 'RELEASE_MODE'
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory
make: *** No targets specified and no makefile found.  Stop.
arms@Gallus:~/GitHub/Bang project/Bang$ which qmake
/usr/bin/qmake
>>> I actually changed the script to have this instead of qmake, and make is in /usr/bin but it didn't work.

**Comment by sephirot47** [comment]
Hi Bill! 
Ye, you need Qt4 for the moment, because Qt5 gave me a couple of problems. 
I haven't been through the process of checking and repairing installation errors...everything is a bit unstable right now tbh. 
One of the next steps is moving to Qt5.

Thanks for reporting the issue and taking the time to try to install Bang !!! 
 I can't really give you a fix to this problem right now :(

**Comment by sephirot47** [comment]
When everything is moved to Qt5 I will let you know, in case you want to try again 👍

**Comment by sephirot47** [comment]
Hi Bill, I moved the project to Qt5, in case you want to try again ;D
However, now that I look at the output of the script, maybe it's not the project itself, but the configuration of your qmake...could it be? You say you installed Qt5 but the path of your qmake is still pointing to the old Qt4 qmake. You can change this by exporting QT_SELECT=5.

**Comment by Bill-Armstrong** [comment]
I tried downloading the new version.  Same result
arms@Gallus:~/GitHub/Bang project/Bang$ ./scripts/fullCompile.sh EDITOR RELEASE_MODE
Full compiling will take a little longer...
You have 5 seconds to stop it.
5...4...3...2...1...Go!
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory
make: *** No rule to make target 'clean'.  Stop.
rm: cannot remove 'Qt_MOCs/*': No such file or directory
rm: cannot remove 'bin/objEditor/*': No such file or directory
rm: cannot remove 'bin/objGame/*': No such file or directory
rm: cannot remove 'ui_*': No such file or directory
BUILD_MODE on compile.sh:       'EDITOR'
RELEASE_OR_DEBUG on compile.sh: 'RELEASE_MODE'
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory
make: *** No targets specified and no makefile found.  Stop.
arms@Gallus:~/GitHub/Bang project/Bang$ I tried to find out why the system keeps referring to qt4:
arms@Gallus:~/GitHub/Bang project/Bang$ which qmake
/usr/bin/qmake
arms@Gallus:~/GitHub/Bang project/Bang$ which make
/usr/bin/make
arms@Gallus:~/GitHub/Bang project/Bang$ 
So some path is right.  I recently installed Kubuntu 16.10 and Qt5.7.1 and it wasn't me who pointed to qt4, so I can't understand why qt4 keeps creeping in.  I saw it before too and it made no sense.  
So I did the thing you suggested and exported QT_SELECT=5 and things got exciting:
BUILD_MODE on compile.sh:       'EDITOR'
RELEASE_OR_DEBUG on compile.sh: 'RELEASE_MODE'
sh: 1: /usr/lib/x86_64-linux-gnu/qt5/bin/rcc: not found
sh: 1: /usr/lib/x86_64-linux-gnu/qt5/bin/rcc: not found
sh: 1: /usr/lib/x86_64-linux-gnu/qt5/bin/uic: not found
sh: 1: /usr/lib/x86_64-linux-gnu/qt5/bin/uic: not found
cd src/Domain/Graphics/FreeType && sh autogen.sh && mkdir build ; cd build && cmake .. && ../configure && cd build ; make
/usr/lib/x86_64-linux-gnu/qt5/bin/uic EngineAssets/EditorWindow.ui -o ui_EditorWindow.h
make: /usr/lib/x86_64-linux-gnu/qt5/bin/uic: Command not found
Makefile:2932: recipe for target 'ui_EditorWindow.h' failed
make: *** [ui_EditorWindow.h] Error 127
make: *** Waiting for unfinished jobs....
autogen.sh: 1: autogen.sh: aclocal: not found
autogen.sh: 55: test: -lt: argument expected
autogen.sh: 59: test: -gt: argument expected
autogen.sh: 67: test: -lt: argument expected
autogen.sh: 71: test: -gt: argument expected
autogen.sh: 1: autogen.sh: libtoolize: not found
autogen.sh: 55: test: -lt: argument expected
autogen.sh: 59: test: -gt: argument expected
autogen.sh: 67: test: -lt: argument expected
autogen.sh: 71: test: -gt: argument expected
autogen.sh: 1: autogen.sh: autoconf: not found
autogen.sh: 55: test: -lt: argument expected
autogen.sh: 59: test: -gt: argument expected
autogen.sh: 67: test: -lt: argument expected
autogen.sh: 71: test: -gt: argument expected
generating `configure.ac'
running `aclocal -I . --force'
autogen.sh: 1: eval: aclocal: not found
error while running `aclocal -I . --force'
/bin/sh: 1: cd: can't cd to build
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/home/arms/GitHub/Bang project/Bang/src/Domain/Graphics/FreeType'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory '/home/arms/GitHub/Bang project/Bang/src/Domain/Graphics/FreeType'
Makefile:973: recipe for target 'FreeTypeTarget' failed
make: *** [FreeTypeTarget] Error 2
***************************************************
I am not that good at Linux to diagnose what happened.  I would be glad to try to help you.   Let me tell you what I am doing.  I have a project on GitHub Animal-motion.  It runs, but I haven't been able to make a movie of the dynamics using Qt5. I can get any frame of output though.  I thought maybe instead, I could make a movie using a game engine like yours.  But then that expands into the whole new idea of making an AI game player that improves by reinforcement learning.  I am going to use the reinforcement learning from Deep-learning-ALN.  I have already tested it on simple problems but controlling the "animal" or human figure with all its joints is something beyond the current state of the art in RL. If you have any suggestions, I would welcome them.   If you want to correspond, please give me your email.   Best wishes,  Bill

**Comment by sephirot47** [comment]
Hi Bill!

Thank you for trying it once more :p

I'm very glad your were willing to use my engine to render your project. However, this game engine is still in a very very early stage of development, so I am pretty sure you would not be able to do much with it (and you would find some bugs hehe)

I also think your best bet for rendering an animal/humanoid and passing inputs to it is using a game engine.
I checked your project, and saw it uses C++. I think the easiest thing you could use for those purposes is Unity (at least for me). However, since integrating such C++ library in Unity can become a bit problematic, I would try Unreal Engine, which is not as straightforward but will work for you, since its scripting language is C++ too.

My email is victorantondominguez@gmail.com

Hope to see your project working soon!
Victor
